### ISSUE TITLE
Endpoint para capas de ecosistemas dentro de una unidad de consulta

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#131]
## Descripción:
Implementar los endpoints que permitan traer la capa de los ecosistema estratégicos dentro de una unidad de consulta.

### Resultado:
* /ea/:ea_id/se/layers/:se_type
* /pa/:pa_id/se/layers/:se_type
* /states/:state_id/se/layers/:se_type
* /basinSubzones/:subzone_id/se/layers/:se_type

### Funcionalidad asociada en el Frontend:
Mapa que permite prender y apagar la capa del ecosistema estratégico seleccionado

## Consideraciones:

**Comment by erikasv** [comment]
Se suspende esta tarea debido a que la información no está disponible, debemos hablar con Jaime para saber cuáles son los pasos a seguir

**Comment by danflop** [comment]
La información se debe sacar de  las tablas de los ecositemas y HF, y los features no deben llevar propiedades.
