### ISSUE TITLE
Endpoint para traer el valor total de hectareas por unidad de consulta

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-backend#135]
## Descripción:
Crear y exponer en el API endpoint para traer el valor total de hectareas por unidad de consulta. Actualmente este dato se muestra en la pestaña de ecosistemas pero se hace sumando las hectareas de cada tipo de cobertura y no se trae el dato del API.

### Resultado:
Endpoint para traer el valor total de hectareas por unidad de consulta

### Funcionalidad asociada en el Frontend:
Dato visualizado en cada pestaña (ecosistemas, paisaje y especies) o en un nivel superior este dato ya que aplica para todo los casos.

## Consideraciones:
Definir donde se visualizaría exactamente y los estilos.

**Comment by erikasv** [comment]
Se crearon los siguientes endpoints:

* /basinSubzones/:subzone_id
* /ea/:ea_id
* /pa/:pa_id
* /states/:state_id

Se creará una tarea adicional para front y back, para eliminar los totales del endpoint de coberturas
