### ISSUE TITLE
Crear e implementar proyecto para el backend del microservicio de Integridad y Bosques

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-backend#181]
## Descripción:
Crear y configurar el proyecto que tendrá los endpoints relacionados con la información de la sección de Integridad y Bosques.

- [x] Crear nuevo proyecto en node.js
- [x] Instalación de dependencias y otras utilidades
- [x] Creación de estructura de directorios
- [x] Documentar proceso genérico para próximos microservicios
---
- [x] Adicionalmente hay que habilitar nuevamente la verificación de la documentación en el workflow de github para features, es sólo descomentar las líneas, hubo que comentarlas por el cambio a monorepo.

### Resultado:
- Proyecto configurado y listo para la construcción de los endpoints.
- Documentación del proceso
- Workflow de github nuevamente verificando la no actualización de documentación en las ramas feature

### Funcionalidad asociada en el Frontend:
Sección de Integridad y Bosques en el módulo de Consultas.

**Comment by cazapatamar** [comment]
@Trjegul84 Por fa cuando tengas el documento de los pasos que seguimos ayer adjuntas el link acá en la tarea y la pasas a "Done"

**Comment by Trjegul84** [comment]
Se documentaron todos los pasos realizados para crear el proyecto para el nuevo microservicio. Se cargaron al drive en un documento word en la carpeta  Biotablero/Microservicios.

[Pasos creación proyecto para nuevo microservicio](https://docs.google.com/document/d/15PvOwWsPBK-OZUqm49EHH9UgAmSQrEXSOf4F9VNDu_M/edit?usp=sharing)
