### ISSUE TITLE
Definir la estructura de los endpoints para el microservicio de Bosques

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-backend#182]
## Descripción:
Discutir y definir la estructura de los endpoints para este microservicio.

### Resultado:
Estructura definida para los microservicios a implementar.

**Comment by erikasv** [comment]
La estructura quedó definida en: https://docs.google.com/spreadsheets/d/1U3P0TsK7wI32aALuHzY9slBz3FMjoPeLsDwfg-PbZ7o/edit#gid=343769423
