### ISSUE TITLE
Implementar endpoints sección Bosques del microservicio

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-backend#183]
## Descripción:
Implementar los endpoints para traer la información de integridad.

### Resultado:
* /sci/hf
* /sci/hf/layer
* /sci/:sci_cat/hf/:hf_pers/layer

## Consideraciones:
Ver primer comentario

**Comment by erikasv** [comment]
Es necesario crear un endpoint en el servicio sancochito para que nos exponga las etiquetas de las áreas protegidas, @cazapatamar va a crear una tarea para esto y va a implementar dicho endpoint.

Yo voy a buscar sobre cuál es la mejor forma de comunicar microservicios para consumir dicho endpoint desde el servicio de bosque en los endpoints de esta tarea, también voy a crear una tarea para esto

Por lo tanto esta tarea se pospone para el siguiente sprint

FYI @danflop @Trjegul84
