### ISSUE TITLE
Solucionar bug cuando se carga un proyecto desde el componente autocomplete en compensaciones

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-backend#184]
## Descripción:
Solucionar bug cuando se carga un proyecto desde el componente autocomplete en compensaciones. Revisar el mensaje en la consola del backend.

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/4c8693c9-0fc1-402f-9e2e-ae0e7fcf3931)

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/42ed19d9-56c8-4eed-8877-92053555bb12)

### Resultado:
Error solucionado

### Funcionalidad asociada en el Frontend:
Selector de compensaciones

**Comment by Trjegul84** [comment]
Cuando se selecciona el proyecto mediante el botón el projectId retornado es un número pero cuando se selecciona mediante el autocomplete envía un objeto.

![BugProjectAutocomplete.png](https://images.zenhubusercontent.com/5f7f6edf564a413e5cdf686c/73f259b8-151c-41c8-b6d4-ac65618bdffd)

**Comment by Trjegul84** [comment]
Se mejora el comportamiento obteniendo el projectId desde el objeto retornado cuando se llama al método loadProject.
