### ISSUE TITLE
Persistencia para endpoints de conectividad sección 2

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-backend#210]
## Descripción:
Persistencia para endpoints de conectividad sección 2

- [x] Gráfico de líneas de conectividad en el tiempo de áreas protegidas - Prot
- [x] Gráfico de líneas de conectividad en el tiempo de áreas protegidas - Prot Conn
- [x] Geometría de todas las áreas protegidas en esa área de consulta

### Resultado:
Persistencia para endpoints

## Consideraciones:
Hacerlo en servicio principal si estos endpoints no han sido copiados a servicio propio de conectividad

**Comment by Trjegul84** [comment]
Se agregaron las persistencias para los datos de la linea de tiempo de los indicadores Prot y ProtConn.
Se agrego el servicio que realiza petición a las persistencias según sea el caso para prot o protcon.
Se creo otro pull-request asociado al commit  3deb6da en el  frontend para que se visualice la gráfica de linea de tiempo.
