### ISSUE TITLE
Spike: Probar Topojson para disminuir el tamaño de una capa.

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#220]
## Descripción:

Revisar que funciones en postgis sirven para generar la geometría ya no en GeoJSON sino en TopoJSON. Quizá la opción más viable sea usar la función `AsTopoJSON` para lo cual es necesario investigar qué extensión o configuración en postgis toca realizar para poder usar esta función.

Cuando se consulta la capa de humedales en la línea del tiempo de huella humana para Meta, el resultado de la consulta es muy larga y no se puede almacenar en un string en el backend y mata el servicio. También la consulta es tan pesada que hace que el postgres consuma hasta 6-7GB de memoria.

## Consideraciones:

Probar que necesita PostGis para usar las funciones de TopoJson.

**Comment by Trjegul84** [comment]
Una de las posibles soluciones es disminuir el tamaño del GeoJson, lo cual optimizaría el tiempo de respuesta no solo para el caso del departamento del Meta sino también para todas las unidades de consulta. 

En este enlace encontrarán algunas recomendaciones para reducir el tamaño de un GeoJson:
[Tips para reducir tamaño de GeoJson](https://mappinggis.com/2015/06/trucos-para-reducir-el-tamano-de-un-geojson/)

Una de las alternativas que podría ser acertada es intentar cambiar el formato que se obtiene desde PostGis para retornar un TopoJson en lugar de un GeoJson. Ya que la otra alternativa es realizar la conversión de GeoJson a TopoJson dentro de la aplicación pero esta alternativa ya la exploraron en paso y resulta en una carga de procesamiento.  
Por lo tanto se expone la opción de extraer el TopoJson desde PostGis. Al respecto se encuentra la siguiente información en este enlace [PostGis AsTopoJson](https://postgis.net/docs/AsTopoJSON.html)

Entre las ventajas de usar TopoJson se encuentran:

- TopoJSOn elimina redundancias, ofreciendo representaciones más compactas de la geometría que GeoJSON. Por ejemplo, el limite compartido entre dos países se representa solo una vez, en lugar de ser duplicado para ambos países, de esta forma, los puntos compartidos solo se representan una vez.
- TopoJSON cuantifica coordenadas, de este modo cada arco está definido por sus coordenadas cuantificadas. La cuantificación consiste en una transformación líneas que consiste en una escala y una traslación que convierte las coordenadas con parte decimal en números enteros.
- Gracias a la eliminación de redundancias y  a la cuantificación de las coordenadas, los ficheros TopoJSON son un **80%** más pequeños que sus equivalentes GeoJSON.

Quedan pendientes las observaciones del equipo de trabajo y la toma de una decisión al respecto.

**Comment by cazapatamar** [comment]
Se realizaron unas primeras pruebas usando la función AsTopoJSON en postgis para tratar de obtener las geometrías en este formato y no en geoJSON. Las pruebas no fueron exitosas ya que la función no fue reconocida desde el cliente de bd dbeaver.

Se verificó que la versión de postgis actual pero igualmente no fue exitoso.

Se recomienda seguir revisando en el próximo sprint

**Comment by danflop** [comment]
Revisar si es necesario habilitar otra extensión para Postgis.

**Comment by erikasv** [comment]
Debido a las actualizaciones de datos y los cambios en la visualización de capas esta tarea ya no es necesaria
