### ISSUE TITLE
Spike: Descarga de datos de gráficas desde el backend

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#235]
## Descripción:

Necesitamos encontrar la forma de descargar todos los datos de las gráficas de una sección (o acordeón grande) ya sea en un archivo comprimido (con múltiples csv) o un .xls con hojas por gráfica

### Resultado:

- Estrategia a implementar para lograr el objetivo

## Consideraciones:
- Tener en cuenta la autenticación del gateway para descargar archivos desde front

**Comment by Trjegul84** [comment]
Se deja en progreso porque aún no se comprende bien como sería el mecanismo para enviar los datos de múltiples endpoints a un solo archivo sin tener a un usuario autenticado. Se debe usar un token o api key pero cómo se otorga éste al usuario? 
Se puede considerar un componente por aparte con un arreglo de ulrs (endpoints) y que se procesen con fetch y Promise.all e ir tomando las respuestas json de cada una. No se tiene claridad de cómo solucionar unir estas respuestas o si en el front se debe usar otro componente para usar los json y generar un archivo excel con multiples pestañas.
Otra posible opción podría ser armar un archivo json en el backend con los datos necesarios de cada petición, como claves de api, tipo de petición y luego procesar este json para que atienda todas las peticiones y genere una respuesta. No se tiene claridad de cómo debería ser esa respuesta. 

Un ejemplo de descarga de archivos con autenticación fue encontrado en este [blog](https://blog.theodo.com/2021/03/authenticated-file-download-with-javascript/) y en este [otro](https://codeburst.io/part-1-jwt-to-authenticate-downloadable-files-at-client-8e0b979c9ac1)

**Comment by erikasv** [comment]
Al final se decidió dejar la solución de cargar a un sevicio de almacenamiento en la nube como la solución definitiva
