### ISSUE TITLE
Cargar rasters de riqueza

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#240]
## Descripción:

Cargar los raster de riqueza a la base de datos. Dependiendo del tamaño del raster puede requerir fragmentarlo.

### Resultado:

- Tabla con los raster (4) de riqueza cargados.
- Documento de [carga de capas](https://docs.google.com/document/d/1pZocsyMaJAlt4pf7_E6zRGCgRt2tGSlB_EdFqLFfb7w/edit#heading=h.pbr7gp451f9m) actualizado con pasos seguidos para la carga de los raster
- Documento E-R actualizado

## Consideraciones:

Se deben habilitar unas extensiones, más info [aquí](https://postgis.net/2014/05/19/postgis-2.0.6_and_2.1.3/)

- Nombre propuesto para la tabla: `raster`
- Guardar el nombre del archivo cuando se genera el sql
- Definir los nombres de los archivos (llaves de las capas)

**Comment by erikasv** [comment]
Agrego acá un poco de información extra a partir de la experiencia con las pruebas anteriores:

La herramienta que he usado para cargar los raster es [raster2pgsql](https://postgis.net/docs/using_raster_dataman.html), un ejemplo del comando es:
```
raster2pgsql -s 3116 -c -I -M 300m_int.tif -F public.m300 > m300.sql
```
Importante verificar el sistema de coordenadas del raster, este se debe pasar en la opción la opción **-s**

Esto genera un sql que luego se carga a la base de datos como cualquier otro, por ejemplo:
```
psql -d pruebaraster -U postgres -f m300.sql
```

Para verificar datos se puede usar la consulta cargada en la rama [feature/spikeRaster](https://github.com/PEM-Humboldt/biotablero-backend/blob/feature/spikeRaster/services/diversity/src/persistence/richness.js), y en lugar de la geometría utilizada desde el parámetro se puede usar la configuración de [cumaribo](https://drive.google.com/file/d/1MeB3LJj0eCI2VSGLBNhiVpHlagxryRFe/view?usp=sharing)

**Comment by cazapatamar** [comment]
Se suben a la base de datos de desarrollo `biotablero-diversity` los 4 raster partidos en una sola tabla llamada `geo_raster` la cual tiene una columna con el nombre del archivo original el cual permite filtrar.

Se documenta el proceso de activar las extensiones de postgis en la base de datos para el momento de hacer la consulta y poder generar la imagen (PNG). [Crear una base de datos vacía - Microservicios](https://docs.google.com/document/d/18Udk8PQufTzckiRH3T4I86uaREspQkoFNWvp-qtgWzw/edit#heading=h.odo4l89zzz2e)

Se documenta el proceso de cargar el raster en la base de datos usando raster2pgsql. [Importar capas en BD relacional](https://docs.google.com/document/d/1pZocsyMaJAlt4pf7_E6zRGCgRt2tGSlB_EdFqLFfb7w/edit#heading=h.hokf4z574u97)

Notas:

- Se deja el sistema de coordenadas por defecto con el que viene el raster (Al no usar la opción `-s`)
- Se hace una partición automática y óptima de cada raster con la opción `-t auto`
