### ISSUE TITLE
Prueba de raster categórico

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#259]
Jaime nos va a enviar antes del 24 de sept un raster con valores categóricos para probar sacar la imagen (en teoría sólo e asignar un color para cada valor en la consulta)

**Comment by cazapatamar** [comment]
Tiempos carga raster categórico

BD DE PRUEBAS

1. RASTER 300 MTS - CORTADO EN BD

CARDER - 1.26s - 9.39 KB

META - 4.7s - 156 KB

CORPOORINOQUIA -  4.9s - 156 KB

2.1 RASTER 90 MTS - CORTADO EN BD

CARDER - 2.98s - 64.68 KB

META - 39.6s - 1.28 MB

CORPOORINOQUIA - 89s - 1.99 MB

2.2 RASTER 90 MTS - NO CORTADO EN BD (Sin hacer el ST_UNION en postgis)

CARDER - 8s - 64.68 KB

META - 37s - 1.28 MB

CORPOORINOQUIA -  73s - 1.99 MB

3. RASTER 30 MTS - CORTADO EN BD

CARDER - 18s - 338.77 KB

META - 359s (6m) - 6.27 MB

CORPOORINOQUIA - Luego de 10 min se cae la consulta

BD LOCAL

2.1 RASTER 90 MTS - CORTADO EN BD

CARDER - 1.74s - 64.68 KB

META - 16.91s - 1.28 MB

CORPOORINOQUIA - 39.17s - 1.99 MB

2.2 RASTER 90 MTS - NO CORTADO EN BD (Sin hacer el ST_UNION en postgis)

CARDER - 5s - 64.68 KB

META - 15.5s - 1.28 MB

CORPOORINOQUIA -  32.8s - 1.99 MB

**Comment by cazapatamar** [comment]
Adicionalmente se hizo la prueba para intentar que en la consulta se asigne el color por medio de un valor específico pero no fue exitoso.

**Comment by cazapatamar** [comment]
Se corrige el comentario anterior y se ajusta la consulta en el backend para el raster categorico:

1: Verde

2: Azul

3: Naranja

* Tener en cuenta que para que los colores se asignen correctamente es necesario asignar a la totalidad de los valores del ráster y estos deben estar en orden descendente.

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/9259b2eb-d393-4391-a494-8c23e4006341)

![image.png](https://images.zenhubusercontent.com/5d6d3a0237b98e000186ce06/e5329cd9-4c5d-40c8-90e7-77c896e8503c)
