### ISSUE TITLE
Actualizar datos y endpoints para coberturas

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-backend#286]
## Descripción:
Actualizar datos y endpoints para la sección de coberturas de acuerdo a los nuevos datos enviados por Jaime.

Analizar como guardar los nuevos datos tanto de las gráficas y los mapas raster. Revisar la estructura de los datos [aqui](https://docs.google.com/document/d/1Sqpz-m--sgWKqdCjNM3rEpH-UohpKt9Xou-F1X43-1o/edit#heading=h.83fj65phkkhv)

### Resultado:
Datos nuevos y endpoints apuntando a nuevos datos.

### Funcionalidad asociada en el Frontend:
Gráfica y mapa de coberturas de la pestaña Paisaje

## Consideraciones:
- Ver si es necesario crear nuevos endpoints o si se pueden modificar los existentes
- Hay que crear el microservicio aparte para ecosistemas (`ecosystems`)
- Hay que crear la base de datos
- No borrar los datos anteriores en esta tarea
- Crear la pestaña nueva y documentar el diagrama [E-R](https://app.diagrams.net/#G1Hnip-jV2dFIziYyOBwiO1jnLXL21Kyfs)

**Comment by Trjegul84** [comment]
- [ ] Base de datos de ecosistemas
- [ ] Creación de micro-servicio
- [ ] Crear nuevos endpoints
- [ ] Documentación y actualización de diagrama ER
