### ISSUE TITLE
Cargar datos y crear endpoints para coberturas de ecosistemas estratégicos

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#290]
## Descripción:
Cargar los datos de coberturas en ecosistemas estratégicos a la base de datos y crear los endpoints correspondientes para:

1. Área total de los ecosistemas estratégicos dentro de la unidad de consulta
1. Área total de cada tipo de ecosistema en la unidad de consulta
1. Área de cada tipo de cobertura dentro del ecosistema en la unidad de consulta. En este caso tener en cuenta que para otros años puede existir la categoría nubes (`X`).
1. Capas de las 3 coberturas para cada tipo de ecosistema estratégico dentro de una unidad de consulta

Adicionalmente se deben realizar los siguientes ajustes:
1. Ajustar la lógica del endpoint de categorías de la unidad de consulta para que contemple la categoría nubes, que en la implementación realizada no se tuvo en cuenta, pero es casualidad que para el año cargado no hubo nubes.
1. Borrar del servicio principal del backend los endpoints correspondientes a la tarea [#286](https://github.com/PEM-Humboldt/biotablero-backend/issues/286), es decir a los de las categorías y capas de coberturas de la unidad de consulta

### Resultado:
- Endpoints para la información de coberturas de ecosistemas estratégicos dentro de una unidad de consulta.
- Los endpoints deben quedar documentados en el documento de [mapeo de endpoints](https://docs.google.com/spreadsheets/d/1U3P0TsK7wI32aALuHzY9slBz3FMjoPeLsDwfg-PbZ7o/edit#gid=0)
- Endpoints viejos de coberturas borrados (sólo los de la unidad de consulta, los de ecosistemas se borrarán después de realizar los ajustes correspondientes en el frontend)
- Endpoints del servicio de ecosistemas tienen en cuenta las nubes.

### Funcionalidad asociada en el Frontend:
- Barra del área y porcentaje de cada ecosistema en la unidad de consulta
- Distribución de área por tipo de cobertura dentro de cada ecosistema estratégico
- Capas de distribución de coberturas dentro del ecosistema estratégico que se abre para ver más información

## Consideraciones:
- Revisar el [documento de actualización de datos de coberturas](https://docs.google.com/document/d/1Sqpz-m--sgWKqdCjNM3rEpH-UohpKt9Xou-F1X43-1o/edit#heading=h.sjf6255o5127).
- Tener en cuenta que al hacer el corte por el área de consulta en los ecosistemas estratégicos el resultado puede ser null
- Revisar y corregir los datos de las tablas en las columnas `geofence_id`  para los casos de CORPONARIÑO (con caracteres o codificación no válida), ATLANTICO (8 en lugar de 08) y ANTIOQUIA (5 en lugar de 05).

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-backend/290?planning-poker) with ZenHub @alegnaaived @cazapatamar @danflop @Trjegul84

**Comment by cazapatamar** [comment]
Se implemetaron todos los endpoints necesarios para las funcionalidades asociadas al front. Se hicieron algunos cambios con los endpoints ya implementados relacionados con coberturas ya que se decidió anteponer `ecosystems` de tal manera que quedan agrupados todos los de este microservicio. 

Se hicieron los cambios en el gateway y en el frontend para que la aplicacion no se rompa.

Solo queda faltando hacer la revisión de la carga de los rasters. Dependiendo del resultado de esta revisión habria que hacer unos pequeños ajustes en las persistencias imeplementadas en esta tarea, ya sea que queden almacenados en `geo_raster` o en otra tabla.

**Comment by cazapatamar** [comment]
Se identificó que el problema con los rasters era la versión de postgis de la maquina desde donde se estaban subiendo la cual era 3.x.x mientras que la del servidor de pruebas es de 2.x.x. Se subieron desde otra maquina con la version correcta incluso sin la opcion -C y ya no se presenta el desplazamiento o comportamiento extraño.

Queda faltando el manejo del caso donde no exista mapa para un ecosistema estratégico específico en un área de consulta (Por ejemplo: `/ecosystems/coverage/se/layer?areaType=states&areaId=94&coverageType=N&seType=Páramo`). Acualmente se retorna una imagen vacia (con valores nulos) y con toda la transparencia. Se espera que el back pueda identificar este caso y darle manejo para enviar la respuesta adecuada al front.
