### ISSUE TITLE
Cargar datos y ajustar endpoints de perdida y persistencia

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#310]
# Descripción

Cargar los raster y los [datos enviados](https://drive.google.com/drive/folders/1JkfahJTjyBlSIzy6bHsNrWYo3Bqq52xI?usp=sharing) para pérdida y persistencia a la base de datos, implementar las consultas relacionadas y actualizar los endpoints.

# Resultado
- Los endpoints de pérdida y persistencia retornan valores reales (actualmente retornan mockups)
- Los endpoints de capas ahora retornan un raster en lugar de un geojson

# Consideraciones
- Creo que los endpoints no necesitan ningún cambio en estructura, pero sí se debe verificar que la documentación quede actualizada.
- En caso de que los endpoints tengan algún cambio en estructura, actualizar el documento del mapeo de endpoints

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-backend/310?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84

**Comment by cazapatamar** [comment]
Evaluar posibiidad de cambiar la palabra `ecoChange` de este grupo de endpoints ya que inicialmente lo dejamos así pero puede no ser muy representativo de la información. Sugiero dejarlo como `forestLP` así como se dejó en el front.

**Comment by cazapatamar** [comment]
Se cargaron los datos en las tablas `forest_lp` y `geo_raster` del microservicio `biotablero_forest`. 

Raster cargados con la versión 2.5 de postgis
