### ISSUE TITLE
Migrar lógica de descarga de archivos AWS a microservicio util

### ISSUE THREAD

**Issue by cazapatamar** [PEM-Humboldt/biotablero-backend#327]
## Descripción:

Migrar lógica de descarga de archivos AWS a microservicio util, el cual está implementado en el microservicio principal y es usado actualmente desde el módulo de compensaciones. Esto con el fin de dar el primer paso en la estandariazción de esta funcionalidad y poder extendarla a otros módulos de biotablero.

El endpoint es `downloadSelectedStrategies`, implementado en `project_strategies.js`. 

Un ejemplo es `/companies/1/projects/1/strategies/download`

Si bien el endpoint seguirá siendo el mismo, el microservicio principal se debe comunicar con el servicio util para subir el archivo deseado a AWS y obtener la url correspondiente. En el archivo [endpoints](https://docs.google.com/spreadsheets/d/1U3P0TsK7wI32aALuHzY9slBz3FMjoPeLsDwfg-PbZ7o/edit#gid=126973602) se documentaron los enpoints que se creen necesarios para el microservicio util y en el archivo del [ER](https://app.diagrams.net/#G1Hnip-jV2dFIziYyOBwiO1jnLXL21Kyfs) se documentaron las tablas.

### Resultado:

- Lógica migrada al microservicio util
- Enpioints para interactuar con el microservicio util desde los demás microservicios
- Lógica borrada del microservicio principal

### Funcionalidad asociada en el Frontend:

Descarga de archivos en el módulo de compensaciones.

## Consideraciones:
- Los endpoints a implementar en el microservicio util son privados para los demás microservicios, por lo tanto no se debe agregar el path al gateway
- Los archivos enlazados en la descripción deben quedar actualizados

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-backend/327?planning-poker) with ZenHub @cazapatamar @danflop @Trjegul84 @ManuelStardust
