### ISSUE TITLE
Actualizar backend de biab

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#357]
### Descripción y resultado

Victor actualizó la rama con los ajustes necesarios para arreglar el problema del raster cortado y envió instrucciones para actualizar otros insumos.

Hacer la actualización del ambiente de azure para probar con el ambiente de desarrollo.

### Consideraciones
Verificar que todo lo que se haga para esta tarea quede registrado en la [#164](https://github.com/PEM-Humboldt/biotablero-scrum/issues/164)

# Actualización 24-07-2023
El alcance de esta tarea se vio afectado por el segundo comentario de Manuel. Ahora se deben hacer ajustes en el front de biotablero.

**Comment by erikasv** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-5f7f96a92b54ca00239a9348/issues/PEM-Humboldt/biotablero-backend/357?planning-poker) with Zenhub @cazapatamar @ManuelStardust

**Comment by ManuelStardust** [comment]
Se realizaron las pruebas con la nueva versión del script suminstrada por Victor en donde se evidencia que el polígono ya no se trunca, sin embargo presenta un error al manejar areas muy pequeñas con resoluciones mayores al área lo cual ya ufe comunicado a Victor. Adicionalmente debido a la cantidad de cambios que presenta el código, es necesario actualizar los parámetros que se envían desde biotablero y encontrar una forma de trabajar con el directorio de salida que suministra Biab para cargar las capas, por tanto no se actualizo el código en el servidor para no interrumpir el funcionamiento actual para el sitio de pruebas de biotablero.

**Comment by erikasv** [comment]
@ManuelStardust ampliar la explicación de los cambios que implicaría en biotablero, cuáles son los cambios específicos que hacen esto necesario y qué significa lo del directorio de salida y por qué es diferente a lo que se tenía antes.

Adicionalmente el que no se actualice el código del servidor no significa que nos e haga el merge en la rama biotablero, precisamente para asegurar la actualización haya funcionado se debe realizar el merge para evitar los problemas que tuvimos antes.

**Comment by ManuelStardust** [comment]
El script de perdida y persistencia actual esta orientado a trabajar con STAC catalog. La última versión del script presenta los siguientes cambios:

1. El nombre del script cambio de 01_pp.R a pp.R
2. Los parámetros de entrada fueron modificados
Parámetros anteriores:
wkt_polygon, epsg_polygon, dir_colection, resolution, folder_output
Parámetros actuales:
WKT_area, collection_path, epsg, resolution, time_period, time_start, time_end
3. El directorio con las colecciones de capas y archivos complementarios a estas tambien cambio de nombre
4. Ya no se crea un directorio adicional para alojar los resultados de salida en el servidor de Biab, por tanto no es necesario enviar un valor para el parámetro del directorio de salida. En cambio se usa el directorio que genera el servidor de Biab al ejecutar un script, el script actual retorna lo valores para diferentes subdirectorios con los resultados de la ejecución, por esto es necesario hacer la modificación en biotablero para capturar el valor de este directorio de salida (dir_png) y asi poder hacer la petición para las capas.

**Comment by ManuelStardust** [comment]
Se generó el documento [Consideraciones al Actualizar el Script de Pérdida y Persistencia
](https://docs.google.com/document/d/1omTyKjuWR1IgGeUSByU3CZwsj0Ykh45jC7e8aVb_RAc) para maneter una guía de como debe mantenerse el código para mantener la compatibilidad con Biotablero.

Adicionalmente se actualizo el documento [Actualización backend BiaB](https://docs.google.com/document/d/1Igfb08EnLRSjQu52MuWhNc6V23vFBTXiX0VweMVBYG8)
