### ISSUE TITLE
Create endpoints to return geofences unit options

### ISSUE THREAD

**Issue by danflop** [PEM-Humboldt/biotablero-backend#58]
We need an endpoint to list options according to:

- departamentos
- municipios
- zonas hidrograficas
- cuencas (basin)
- subzonas hidrograficas (sub-basin)
- áreas protegidas
- ecosistemas estrategicos

**Comment by erikasv** [comment]
@alegnaaived Se hizo un cambio en la estructura de los endpoints:
* listEA pasó de "/ea" a "geofences/ea"
* BiomeBySubzone pasó de "/geofences/ea/:ea_id/biome/:name_biome/subzone" a "/ea/:ea_id/biome/:name_biome/subzone"
* EAByBioticUnit pasó de "/geofences/ea/:ea_id/bioticUnit" a "/ea/:ea_id/bioticUnit"
* EAByCompensationFactor pasó de "/geofences/ea/:ea_id/compensationFactor" a "/ea/:ea_id/compensationFactor"
* EAByGeneralBiome pasó de "/geofences/ea/:ea_id/generalBiome" a "/ea/:ea_id/generalBiome"

Este cambios se puede ver en este [commit](https://github.com/PEM-Humboldt/biotablero-backend/commit/f34646524638ddfa96461227328769e7c4a1d000) 

Los endpoints relacionados con este issue están agrupados en "Geofences".

**Comment by erikasv** [comment]
@alegnaaived Hacer caso omiso al primer cambio del mensaje anterior. Se ha eliminado por completo el prefijo "/geofences", así que "/ea" sigue siendo el endpoint para listar las autoridades ambientales.

Los endpoints de este issue quedaron bajo diferentes grupos:
* /basinAreas
* /basinSubzones
* /basinZones
* /municipalities
* /pa/category/:category_name
* /pa/categories
* /se/paramos
* /se/types
* /se/dryForest
* /se/wetlands
* /states
* /states/:state_id/municipalities

**Comment by erikasv** [comment]
Se ha determinado cambiar los endpoints bajo "/se" para que queden solamente: "/se" (todos los ecosistemas estratégicos) y "/se/primary" (sólo los nombres primarios, es decir, sin la clase secundaria)

**Comment by erikasv** [comment]
@alegnaaived @danflop  Ya está actualizado el PR
