### ISSUE TITLE
Create endpoints to retrieve ecosystem information for every geofence

### ISSUE THREAD

**Issue by erikasv** [PEM-Humboldt/biotablero-backend#60]
Create endpoints with ecosytems information for every geofence, for example:
* /{geofence}/:{id}/se
* /{geofence}/:{id}/pa
* /{geofence}/:{id}/coverage

Put the final endpoints when the issue is finished

**Comment by erikasv** [comment]
Se crearon los mockups de los siguientes endpoints:
* /pa/:category/coverage
* /pa/:category/pa
* /pa/:category/se
* /states/:state_id/coverage
* /states/:state_id/pa
* /states/:state_id/se
* /ea/:ea_id/coverage
* /ea/:ea_id/pa
* /ea/:ea_id/se
* /basinSubzones/:subzone_id/coverage
* /basinSubzones/:subzone_id/pa
* /basinSubzones/:subzone_id/se

**Comment by alegnaaived** [comment]
Questions:
1. What is the basin's area to search? Are basinSubzones or basinAreas?
2. There is missing the three search options by strategic ecosystems

**Comment by erikasv** [comment]
1. basinSubzones
2. Strategic ecosystems have a different behavior, we decided to let that category for other issue
